name: Robopomodoro
description: Robowerkz pomodoro app

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  mockito: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/robopomodoro-background.png
  fonts:
    - family: Merkury
      fonts:
      - asset: assets/fonts/merkury_light.ttf
      - asset: assets/fonts/merkury_bold.ttf
        weight: 600
