name: Robopomodoro
description: Robowerkz pomodoro app

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  test: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/robopomodoro-background.png
