name: Robopomodoro
description: Robowerkz pomodoro app
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^0.5.6+3" 
  mockito: "^4.1.1"
  intl: "^0.16.1"
  provider: "^4.0.5+1"
  flutter_hooks: "^0.9.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/robopomodoro-background.png
  fonts:
    - family: Merkury
      fonts:
      - asset: assets/fonts/merkury_light.ttf
      - asset: assets/fonts/merkury_bold.ttf
        weight: 600
