name: Robopomodoro
description: Robowerkz pomodoro app

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
    path: ../flutter-plugins/packages/shared_preferences

  mockito: "^2.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/robopomodoro-background.png
